
CREATE DATABASE IF NOT EXISTS ukol_db;
USE ukol_db;

CREATE TABLE IF NOT EXISTS ukoly (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nazev VARCHAR(255) NOT NULL,
    popis TEXT NOT NULL,
    stav VARCHAR(50) NOT NULL,
    termin DATE NOT NULL
);
